targets:
  $default:
    builders:
      isolate_helps|isolate_builder:
        enabled: true
        options:
          input_files: 'lib/isolate/*.dart'
          output_file: 'lib/isolate_output/output.dart'
          sort_assets: false
          header: '// Header specified in build.yaml.'
          footer: '// Footer specified in build.yaml.'
