name: example

description: Example demonstrating how to use the library isolate_helps.

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  isolate_helps:
    path: ./../

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  lints: ^1.0.1
  source_gen: ^1.1.1
  test: ^1.19.3

dependency_overrides:
  # source_gen:
  #   git:
  #     url: git@github.com:dart-lang/source_gen.git
  #     ref: master
  #     path: source_gen
