builders:
  isolate_builder:
    import: "package:isolate_helps/builder.dart"
    builder_factories: ["isolateBuilder"]
    build_extensions: {"lib/$lib$": ["*.dart"]}
    auto_apply: root_package
    build_to: source