name: isolate_helps
version: 0.0.3
description: Example demonstrating how to use the library merging_builder.
repository: https://github.com/modeckrus/isolate_helps

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  analyzer: ^2.7.0
  async: ^2.8.2
  build: ^2.1.1
  build_config: ^1.0.0
  merging_builder: ^0.2.3
  quote_buffer: ^0.2.3
  source_gen: ^1.1.1

dev_dependencies:
  lints: ^1.0.1

dependency_overrides: null

# source_gen:
#   git:
#     url: git@github.com:dart-lang/source_gen.git
#     ref: master
#     path: source_gen
